package org.shared;

public enum MessageType {
    USER_CREATE,
    USER_LOG_IN,
    USER_SEARCH,
    CONVERSATION_CREATE,
    CONVERSATION_SEARCH,
    MESSAGE_SEND,
    CONVERSATION_DISPLAY,
    READ_TARGET_AVATAR,
    CONVERSATION_GET,
    ONLINE_USERS_FETCH,
    USER_EXIT,
    NEW_MESSAGE_NOTIFY
}
