package org.shared;

public enum ServerResponseMessage {
    USER_CREATED,
    USER_LOGGED_IN,
    USER_SEARCHED,
    CONVERSATION_CREATED,
    CONVERSATION_SEARCHED,
    MESSAGE_SENT,
    CONVERSATION_DISPLAYED,
    READ_TARGET_AVATAR,
    CONVERSATION_GET,
    ONLINE_USERS_FETCHED,
    USER_EXITED,
    NEW_MESSAGE_NOTIFIED
}
