import java.util.Properties

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.0.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    id("java-library")
    id("maven-publish")
}

group = "shared-lib"

val versionFile = file("version.properties")

// Load current version
val properties = Properties()
versionFile.inputStream().use { properties.load(it) }

val currentVersion = properties.getProperty("version") ?: "1.0.0"

fun incrementVersion(version: String): String {
    val parts = version.split(".").map { it.toInt() }
    val major = parts[0]
    val minor = parts[1]
    val patch = parts[2] + 1
    return "$major.$minor.$patch"
}

// Define a task to update version
tasks.register("updateVersion") {
    doLast {
        val newVersion = incrementVersion(currentVersion)
        properties.setProperty("version", newVersion)
        versionFile.outputStream().use { properties.store(it, null) }
        println("Updated version to $newVersion")
        // Set project version
        project.version = newVersion
    }
}

// Ensure version updates before publish
tasks.named("publish") {
    dependsOn("updateVersion")
}

// Initialize project version
project.version = currentVersion


publishing {
    publications {
        create<MavenPublication>("mavenJava") {
            from(components["java"])
            artifactId = "voicechat-common"
        }
    }
    repositories {
        maven {
            url = uri("https://maven.pkg.github.com/lauraVDL2/VoiceChat-Common")
            credentials {
                username = System.getenv("COMMON_USERNAME")
                password = System.getenv("COMMON_TOKEN")
            }
        }
    }
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation("org.neo4j:neo4j-ogm-core:4.0.19")
    implementation("org.neo4j:neo4j-ogm-bolt-driver:4.0.19")
    implementation("org.projectlombok:lombok:1.18.28")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    modularity.inferModulePath = true
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}